version: '3'

services:
    db:
        image: mcmoe/mssqldocker:v2019-latest
        container_name: intranet-production
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: 1p@sswordY
          MSSQL_DB: intranet-production
          MSSQL_USER: intranet
          MSSQL_PASSWORD: 1p@sswordY
        ports:
            - "1433:1433"

    postcomment.api:
        container_name: intranet_api
        depends_on:
           - db
        image: intranet.api
        build:
          context: .
        ports:
          - "8080:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=staging
