version: '3'

services:
    db:
        image: mcmoe/mssqldocker:v2019-latest
        container_name: intranet-production
        environment:
          ACCEPT_EULA: Y
          SA_PASSWORD: 1p@sswordY
          MSSQL_DB: intranet-production
          MSSQL_USER: intranet
          MSSQL_PASSWORD: 1p@sswordY
          SQLCOLLATION: SQL_Latin1_General_CP1_CI_AS
        ports:
            - "1433:1433"

    intranet.api:
        container_name: intranet_api
        depends_on:
           - db
        image: intranet.api
        build:
          context: .
          dockerfile: dockerfile
        ports:
          - "5000:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=staging
